language: java
jdk:
  - oraclejdk7

before_script:
  - ./gradlew initGitDependencies

script:
  - ./gradlew cleanTest test cobertura

branches:
  only:
    - master

after_success:
- ./gradlew coveralls
